version: '3.8'

services:
  qlever-control:
    # Use the latest image from GitHub Container Registry
    image: ghcr.io/gipplab/qlever-control:latest
    
    volumes:
      # Mount Docker socket to allow running Docker commands on host
      # SECURITY WARNING: Mounting the Docker socket gives this container full control over
      # the Docker daemon, equivalent to root access on the host. Only use in trusted environments.
      # Note: In swarm mode, this will use the socket from the node where the container runs.
      # This also limits horizontal scaling - the service must run with replicas: 1
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount workspace directory for working with files
      - /public/dumps/public:/public/dumps/public
      - /srv:/srv
    
    environment:
      # Set to "true" to test Docker connectivity on startup
      - TEST_DOCKER=false
    
    # Keep container running with stdin and tty
    stdin_open: true
    tty: true
    
    # Deployment configuration for Docker Swarm
    deploy:
      # Restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
         constraints:
           - node.role == worker
  qlever:
    image: adfreiburg/qlever:REBUILD-INDEX-BETA
    ports:
      - "7001:7001"
    volumes:
      - /srv:/srv
      - /srv/qlever:/index
      - /etc/localtime:/etc/localtime
    command:
      - "-c qlever-server -i wikidata -j 8 -p 7001 -m 20G -c 15G -e 5G -k 200 -s 600s -a wikidata_4nOICSfIFEoE > wikidata.server-log.txt 2>&1"
    entrypoint:
      - "bash"
    environment:
      QLEVER_PROFILE: /etc/profile.d/qlever.sh
      QLEVER_IS_RUNNING_IN_CONTAINER: 1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
         constraints:
           - node.role == worker
      labels:
        - "com.qlever.service=qlever-sparql-endpoint"
    networks:
      - qlever_network

  qlever-ui:
    image: adfreiburg/qlever-ui:latest
    ports:
      - "7000:7000"
    volumes:
      - /srv/qlever:/app/db
    environment:
      QLEVERUI_DATABASE_URL: "sqlite:////app/db/wikidata.ui-db.sqlite3"
      VIRTUAL_ENV: "/env"
    command:
      - "gunicorn --bind :7000 --workers 3 --limit-request-line 10000 qlever.wsgi:application"
    deploy:
      placement:
         constraints:
           - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "com.qlever.service=qlever-ui"
    networks:
      - qlever_network

networks:
  qlever_network:
    driver: overlay
    attachable: true
